task :default => :struct
BUILDDIR="builddir"

# TODO use method missing to conjur up a
# method to build _any_ C program
desc "build structstruct"
task :struct do
    sh "make structstruct"
end

desc "build it"
task :build => 'builddir' do
    sh "cd #{BUILDDIR} && ninja"
end

task 'builddir' do
    if not File.directory?(BUILDDIR) then
        sh "meson #{BUILDDIR}"
    end
end

# test regular
task :clean do
    sh "rm -rf #{BUILDDIR}"
end

# test cli app
#task :address do
#    sh "#{BUILDDIR}/daytimeserver"
#end

#rule "" do |t|
#    t.name
#    sh "#{BUILDDIR}/#{t}"
#end
